version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram_auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: telegram_auth_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: